creating numpy arrays

In [2]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and #3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:

# Added a comma after [1,2]
c = np.array([[[1,2], [3,4], [5,6], [7,8]]]) 
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [5]:
#dtype

np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random

np.random.random((3,4))

array([[0.71923809, 0.66876953, 0.69446436, 0.07469982],
       [0.64857291, 0.61949685, 0.15541487, 0.82614131],
       [0.01309176, 0.5152333 , 0.95598797, 0.68179503]])

In [11]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.indentity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [13]:
a1 = np.arange(10)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1 # 1D Array
a2 # matrics
a3 # tensor



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
#ndim
a1.ndim

1

In [15]:
#shape
a1.shape

(10,)

In [16]:
a1.size

10

changing datatypes


In [17]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# Scaler operations

# arithmetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [26]:
#relational 

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
# vector operation
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [31]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[42., 57.,  2.],
       [62., 51.,  7.],
       [72., 85., 46.]])

In [38]:
# max/mean/sum/prod

np.max(a1, axis=1)

array([57., 62., 85.])

In [39]:
# mean/median/std/var

np.mean(a1)

np.float64(47.111111111111114)

In [41]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])