creating numpy arrays

In [6]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# 2D and #3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:

# Added a comma after [1,2]
c = np.array([[[1,2], [3,4], [5,6], [7,8]]]) 
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [14]:
#dtype

np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [16]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# np.random

np.random.random((3,4))

array([[0.63448247, 0.65512963, 0.81362675, 0.35523484],
       [0.29108508, 0.15403581, 0.34447994, 0.44390358],
       [0.39941479, 0.00743843, 0.76822742, 0.67191703]])

In [22]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
# np.indentity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1 # 1D Array
a2 # matrics
a3 # tensor



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#ndim
a1.ndim

1

In [29]:
#shape
a1.shape

(10,)

In [30]:
a1.size

10