creating numpy arrays

In [63]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [64]:
# 2D and #3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [65]:

# Added a comma after [1,2]
c = np.array([[[1,2], [3,4], [5,6], [7,8]]]) 
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [66]:
#dtype

np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [67]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [68]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
# np.random

np.random.random((3,4))

array([[0.15454412, 0.2460162 , 0.4925613 , 0.61230627],
       [0.17493115, 0.46556133, 0.99952132, 0.18543321],
       [0.90505773, 0.35361076, 0.31741181, 0.4163601 ]])

In [72]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [73]:
# np.indentity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [74]:
a1 = np.arange(10)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1 # 1D Array
a2 # matrics
a3 # tensor



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
#ndim
a1.ndim

1

In [76]:
#shape
a1.shape

(10,)

In [77]:
a1.size

10

changing datatypes


In [78]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [79]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
# Scaler operations

# arithmetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [81]:
#relational 

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [82]:
# vector operation
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [83]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 7., 86., 58.],
       [52., 11., 96.],
       [ 8., 32., 31.]])

In [84]:
# max/mean/sum/prod

np.max(a1, axis=1)

array([86., 96., 32.])

In [85]:
# mean/median/std/var

np.mean(a1)

np.float64(42.333333333333336)

In [86]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [87]:
# log and exponents

np.log()

TypeError: log() takes from 1 to 2 positional arguments but 0 were given

# indexing and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:2:,:3:2]

array([[4, 6]])

In [ ]:
a2[1:2:,:4:3]

array([[4, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

iterating 

In [ ]:
a1

for i in a1:
    print(i)

[99. 51. 18.]
[27. 19. 85.]
[16. 48. 92.]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
    print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [ ]:
for i in np.nditer():
    print(iter)

TypeError: nditer() missing required argument 'op' (pos 1)