creating numpy arrays

In [27]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [28]:
# 2D and #3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [29]:

# Added a comma after [1,2]
c = np.array([[[1,2], [3,4], [5,6], [7,8]]]) 
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [30]:
#dtype

np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [31]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [32]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# np.random

np.random.random((3,4))

array([[0.55971624, 0.34499126, 0.37472446, 0.90983554],
       [0.6111379 , 0.1012542 , 0.1026167 , 0.32719641],
       [0.07340678, 0.03163967, 0.10228   , 0.30104729]])

In [36]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [37]:
# np.indentity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [38]:
a1 = np.arange(10)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1 # 1D Array
a2 # matrics
a3 # tensor



array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
#ndim
a1.ndim

1

In [40]:
#shape
a1.shape

(10,)

In [41]:
a1.size

10

changing datatypes


In [42]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [43]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# Scaler operations

# arithmetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [45]:
#relational 

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
# vector operation
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [47]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 4., 21., 34.],
       [17., 76., 54.],
       [53., 62., 42.]])

In [48]:
# max/mean/sum/prod

np.max(a1, axis=1)

array([34., 76., 62.])

In [49]:
# mean/median/std/var

np.mean(a1)

np.float64(40.333333333333336)

In [50]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [51]:
# log and exponents

np.log()

TypeError: log() takes from 1 to 2 positional arguments but 0 were given

# indexing and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:2:,:3:2]

array([[4, 6]])

In [ ]:
a2[1:2:,:4:3]

array([[4, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

iterating 

In [ ]:
a1

for i in a1:
    print(i)

[99. 51. 18.]
[27. 19. 85.]
[16. 48. 92.]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
    print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [ ]:
for i in np.nditer():
    print(iter)

TypeError: nditer() missing required argument 'op' (pos 1)

# numy array vs python lists

In [ ]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []

for i in range(len(a)):
    c.append([i] + b[i])
    

TypeError: can only concatenate list (not "int") to list

In [ ]:
# memory

a = [i for i in range(10000000)]

import sys

sys.getsizeof(a)


89095160

In [ ]:
a = np.arange(10000000, dtype = np.int32)
sys.getsizeof(a)

40000112

In [ ]:
#convenience


Advanced indexing

In [ ]:
# normal indexing and slicing

a = np.arange(24).reshape(6,4)
a



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# fancing intexing

a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
# boolean indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[98, 76,  1, 91],
       [46, 15, 92, 32],
       [25, 89, 48, 56],
       [34, 63, 39, 85],
       [51, 79, 64, 78],
       [31, 77, 38, 77]], dtype=int32)

In [ ]:
np.random.randint(1,100,24).reshape(6,4)

array([[ 3, 23, 20,  1],
       [57, 30, 78, 14],
       [30,  9,  3, 83],
       [26,  8, 64, 52],
       [50, 33, 58, 50],
       [67, 25, 14, 25]], dtype=int32)

In [ ]:
# find all number greater than 50
a[a > 50] 

array([98, 76, 91, 92, 89, 56, 63, 85, 51, 79, 64, 78, 77, 77],
      dtype=int32)

In [ ]:
# find out even numbers

a[a % 2 == 0]

array([98, 76, 46, 92, 32, 48, 56, 34, 64, 78, 38], dtype=int32)

In [ ]:
# find all number greater than 50 and are even
(a > 50) & (a % 2 == 0)

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [ ]:
# find all number not divisible by 7

a[~(a % 7 == 0)]

array([76,  1, 46, 15, 92, 32, 25, 89, 48, 34, 39, 85, 51, 79, 64, 78, 31,
       38], dtype=int32)

# Broadcasting 

In [ ]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [53]:
# more example 
import numpy as np 
a = np.arange(12).reshape(4,3)
b= np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [54]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [55]:
a = np.arange(3).reshape(1,3)
b =  np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [57]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [59]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 